-- Deprecated helper file.
-- Use supabase/schema.sql as the single source of truth for local setup.
-- This file is intentionally kept free of executable schema changes so it
-- cannot drift from schema.sql or change deployment behavior by accident.
